Vagrant::Config.run do |config|
  config.vm.host_name = 'go'
  config.vm.box = 'lucid64'
  config.vm.customize do |vm|
    vm.memory_size = 1024 # MB
  end
  config.vm.share_folder('vagrant-share', '/tmp/vagrant-share', './share')
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "go.pp"
  end
  config.vm.network("33.33.33.2")
end
